meta-dumpling: qtbase: Remove invalid PACKAGECONFIG examples
Qt6 never had this PACKAGECONFIG, so remove this because since Wrynose
release this results in a QT error:
 ERROR: qtbase-6.11.2-r0 do_configure: QA Issue: qtbase: invalid
 PACKAGECONFIG(s): examples [invalid-packageconfig]

Signed-off-by: Alexander Stein <alexander.stein@ew.tq-group.com>